In [2]:
import numpy as np

In [7]:
belief = np.array([0.207078, 0.108909, 0.017499, 0.000988])

transition_matrix = np.array([0.05, 0.05, 0.85, 0.05])
for i in range(3):
    transition_matrix = np.vstack([transition_matrix, np.array([0.05, 0.05, 0.85, 0.05])])
    
print(transition_matrix)
print(transition_matrix.shape)

[[0.05 0.05 0.85 0.05]
 [0.05 0.05 0.85 0.05]
 [0.05 0.05 0.85 0.05]
 [0.05 0.05 0.85 0.05]]
(4, 4)


In [8]:
transitioned_belief = belief @ transition_matrix.T
transitioned_belief_2 = np.matmul(belief.reshape(1, -1), transition_matrix.T)
print(transitioned_belief)
print(transitioned_belief_2)

[0.0307229 0.0307229 0.0307229 0.0307229]
[[0.0307229 0.0307229 0.0307229 0.0307229]]


In [9]:
belief.sum() * 0.05

0.0167237