In [1]:
import numpy as np

In [18]:
dimension = 5
eps = 10**(-5)
b = np.zeros((dimension, dimension)) + eps
# print(test_matrix)

a = np.eye(dimension) * (1 - dimension * eps)

transition_matrix = a + b
print(a)
print(b)
print(transition_matrix)

[[0.99995 0.      0.      0.      0.     ]
 [0.      0.99995 0.      0.      0.     ]
 [0.      0.      0.99995 0.      0.     ]
 [0.      0.      0.      0.99995 0.     ]
 [0.      0.      0.      0.      0.99995]]
[[1.e-05 1.e-05 1.e-05 1.e-05 1.e-05]
 [1.e-05 1.e-05 1.e-05 1.e-05 1.e-05]
 [1.e-05 1.e-05 1.e-05 1.e-05 1.e-05]
 [1.e-05 1.e-05 1.e-05 1.e-05 1.e-05]
 [1.e-05 1.e-05 1.e-05 1.e-05 1.e-05]]
[[9.9996e-01 1.0000e-05 1.0000e-05 1.0000e-05 1.0000e-05]
 [1.0000e-05 9.9996e-01 1.0000e-05 1.0000e-05 1.0000e-05]
 [1.0000e-05 1.0000e-05 9.9996e-01 1.0000e-05 1.0000e-05]
 [1.0000e-05 1.0000e-05 1.0000e-05 9.9996e-01 1.0000e-05]
 [1.0000e-05 1.0000e-05 1.0000e-05 1.0000e-05 9.9996e-01]]


In [28]:
evals_a, _ = np.linalg.eig(a)
evals_a = evals_a.real
evals_a[np.isclose(evals_a, 0)] = 0

In [29]:
evals_b, _ = np.linalg.eig(b)
evals_b = evals_b.real
evals_b[np.isclose(evals_b, 0)] = 0
#print(evals_b)

In [30]:
evals_t, _ = np.linalg.eig(transition_matrix)
evals_t = evals_t.real
evals_t[np.isclose(evals_t, 0)] = 0
#print(evals_t)
#evals[np.isclose(evals, 1)] = -1
#return max(evals)

In [32]:
print(evals_a)
print(evals_b)
print(evals_t)
print(type(evals_a))

[0.99995 0.99995 0.99995 0.99995 0.99995]
[5.e-05 0.e+00 0.e+00 0.e+00 0.e+00]
[0.99995 1.      0.99995 0.99995 0.99995]
<class 'numpy.ndarray'>
