In [6]:
import numpy as np

import utils
from Z_oldies.switchingBanditEnv_aistats import SwitchingBanditEnvAistats

In [3]:
num_states = 5
num_actions = 18
num_obs = 5
delta = 0.1

observation_multiplier = 20
# transition_multiplier = 15
transition_multiplier = 20
num_experiments = 5

In [4]:
switching = SwitchingBanditEnvAistats(num_states=num_states,
                               num_actions=num_actions,
                               num_obs=num_obs,
                               transition_multiplier=transition_multiplier,
                               observation_multiplier=observation_multiplier)
real_transition_matrix = switching.transition_matrix

Sigma min is 0.016640626588496615
Sigma min is 0.023266296349655154
Sigma min is 0.007411360856284326
Sigma min is 0.0019050818565488363
Sigma min is 0.018565188052727524
Sigma min is 0.01789225054494508
Sigma min is 0.010879306389544386
Sigma min is 0.0019815184695807426
Sigma min is 0.003606878820652603
Sigma min is 0.2694655521147165
Sigma min is 0.015211470980552212
Sigma min is 0.004700103414270108
Sigma min is 0.001846401474031653
Sigma min is 0.0037979858183199494
Sigma min is 0.21780142154682153
Sigma min is 0.008516351862318304
Sigma min is 0.01967811454280854
Sigma min is 0.002393200963057624
(5, 5)
Kronecker sigma min is 0.0002769104532577714
Product sigma min is 0.0002769104532577805
(5, 5)
Kronecker sigma min is 0.0003871657496519124
Product sigma min is 0.00038716574965191327
(5, 5)
Kronecker sigma min is 0.0001233296885220269
Product sigma min is 0.000123329688522028
(5, 5)
Kronecker sigma min is 3.170175579535299e-05
Product sigma min is 3.1701755795349056e-05
(5, 5)
Kr

In [7]:
# check the spectral gap between the original matrix and the iterated one
second_eig = utils.compute_second_eigenvalue(real_transition_matrix)
original_spectral_gap = 1 - second_eig
print(f"Original spectral gap is {original_spectral_gap}")

iterated_mat = real_transition_matrix
for i in range(1000):
    iterated_mat = np.matmul(iterated_mat, real_transition_matrix)
    second_eig = utils.compute_second_eigenvalue(iterated_mat)
    spectral_gap = 1 - second_eig
    print(f"Spectra gap is {spectral_gap}")

Original spectral gap is 0.4109789385883069
Spectra gap is 0.6530541892134428
Spectra gap is 0.7956416102781615
Spectra gap is 0.8796286043776586
Spectra gap is 0.9290987127869215
Spectra gap is 0.958237648550297
Spectra gap is 0.975401095422048
Spectra gap is 0.9855107271159299
Spectra gap is 0.9914655131067415
Spectra gap is 0.9949730074715287
Spectra gap is 0.9970389955251714
Spectra gap is 0.9982559060013915
Spectra gap is 0.998972691901738
Spectra gap is 0.9993948938935651
Spectra gap is 0.9996435797589208
Spectra gap is 0.9997900609712908
Spectra gap is 0.999876341490478
Spectra gap is 0.9999271625334688
Spectra gap is 0.9999570971981531
Spectra gap is 0.9999747293461188
Spectra gap is 0.9999851150526284
Spectra gap is 0.9999912324525001
Spectra gap is 0.9999948357298651
Spectra gap is 0.9999969581361239
Spectra gap is 0.9999982082781109
Spectra gap is 0.9999989446380715
Spectra gap is 0.9999993783695966
Spectra gap is 0.9999996338466002
Spectra gap is 0.9999997843279357
Spectra 

In [10]:
# check the spectral gap between the original matrix and the iterated one
original_second_eig = utils.compute_second_eigenvalue(real_transition_matrix)
original_spectral_gap = 1 - original_second_eig
print(f"Original spectral gap is {original_spectral_gap}")

iterated_mat = real_transition_matrix
for i in range(40):
    iterated_mat = np.matmul(iterated_mat, real_transition_matrix)
    second_eig = utils.compute_second_eigenvalue(iterated_mat)
    spectral_gap = 1 - second_eig
    
    # theoretical
    theo_spectral_gap = 1 - original_second_eig**(i+2)
    print(f"Spectra gap is {spectral_gap}, theo is {theo_spectral_gap}")
    

Original spectral gap is 0.4109789385883069
Spectra gap is 0.6530541892134428, theo is 0.6530541892134425
Spectra gap is 0.7956416102781615, theo is 0.7956416102781615
Spectra gap is 0.8796286043776586, theo is 0.8796286043776582
Spectra gap is 0.9290987127869215, theo is 0.9290987127869215
Spectra gap is 0.958237648550297, theo is 0.9582376485502971
Spectra gap is 0.975401095422048, theo is 0.9754010954220479
Spectra gap is 0.9855107271159299, theo is 0.9855107271159297
Spectra gap is 0.9914655131067415, theo is 0.9914655131067412
Spectra gap is 0.9949730074715287, theo is 0.9949730074715285
Spectra gap is 0.9970389955251714, theo is 0.9970389955251711
Spectra gap is 0.9982559060013915, theo is 0.9982559060013915
Spectra gap is 0.998972691901738, theo is 0.9989726919017379
Spectra gap is 0.9993948938935651, theo is 0.9993948938935648
Spectra gap is 0.9996435797589208, theo is 0.9996435797589208
Spectra gap is 0.9997900609712908, theo is 0.999790060971291
Spectra gap is 0.9998763414904

In [8]:
random_matrix = np.random.random(size=(num_states, num_states)) * 0.1
perturbed_transition_matrix = real_transition_matrix + random_matrix
perturbed_transition_matrix = perturbed_transition_matrix / perturbed_transition_matrix.sum(axis=1)[:, None]
print(f"Real transition matrix is {real_transition_matrix}")
print(f"Perturbed transition matrix is {perturbed_transition_matrix}")

transition_distance = np.absolute(real_transition_matrix.reshape(-1) -
                              perturbed_transition_matrix.reshape(-1))
print(f"Distance vector is {abs(np.sum(transition_distance))}")

Real transition matrix is [[0.54210526 0.01578947 0.12631579 0.18947368 0.12631579]
 [0.21634615 0.59615385 0.04326923 0.01442308 0.12980769]
 [0.04663212 0.17098446 0.70466321 0.06217617 0.01554404]
 [0.17030568 0.11790393 0.03930131 0.6069869  0.06550218]
 [0.1640625  0.1640625  0.10546875 0.12890625 0.4375    ]]
Perturbed transition matrix is [[0.447583   0.02457175 0.17705212 0.18838727 0.16240586]
 [0.20179412 0.52296069 0.08595904 0.02896905 0.16031709]
 [0.04152947 0.18260469 0.59280221 0.11507306 0.06799057]
 [0.14236706 0.13747211 0.07743499 0.5421664  0.10055944]
 [0.1776935  0.16685033 0.15763614 0.12023754 0.37758249]]
Distance vector is 0.9233257122986802


In [25]:
belief = np.ones(shape=num_states) * 1/num_states
cumulated_difference = 0
all_prob = 0
distance_vec = np.zeros(shape=num_states)
for first_state in range(num_states):
    for second_state in range(num_states):
        real_prob = belief[first_state] * real_transition_matrix[first_state, second_state]
        all_prob += real_prob
        perturbed_prob = belief[first_state] * perturbed_transition_matrix[first_state, second_state]
        distance = real_prob - perturbed_prob
        distance_vec[second_state] += distance

print(distance_vec)
belief_distance = np.absolute(distance_vec)
print(f"Sum of distances is {np.sum(belief_distance)}")

[ 0.02569691  0.00608693 -0.01437324  0.00142655 -0.01883715]
Sum of distances is 0.06642078137007809


In [21]:
belief = np.ones(shape=num_states) * 1/num_states
cumulated_difference = 0
all_prob = 0
final_belief = np.zeros(shape=num_states)
for first_state in range(num_states):
    for second_state in range(num_states):
        for third_state in range(num_states):
            real_prob = belief[first_state] * real_transition_matrix[first_state, second_state] * real_transition_matrix[second_state, third_state]
            final_belief[third_state] += real_prob

print(final_belief)

[0.23866846 0.21445968 0.20583093 0.20053077 0.14051017]


In [22]:
after_first_belief = np.dot(belief, real_transition_matrix)
after_second_belief = np.dot(after_first_belief, real_transition_matrix)
print(after_second_belief)

[0.23866846 0.21445968 0.20583093 0.20053077 0.14051017]


In [19]:
real_belief = np.dot(belief, real_transition_matrix)
print(real_belief)
perturbed_belief = np.dot(belief, perturbed_transition_matrix)
print(perturbed_belief)

belief_distance = np.absolute(real_belief.reshape(-1) -
                              perturbed_belief.reshape(-1))
print(f"Distance vector is {np.sum(belief_distance)}")

belief_distance = real_belief.reshape(-1) - perturbed_belief.reshape(-1)
print(f"Distance vector is {belief_distance}")


[0.22789034 0.21297884 0.20380366 0.20039322 0.15493394]
[0.20219343 0.20689191 0.2181769  0.19896666 0.17377109]
Distance vector is 0.06642078137007806


In [30]:
real = real_transition_matrix
perturbed_transition_matrix = switching.generate_transition_matrix_v2(transition_multiplier=20)
perturbed = perturbed_transition_matrix
distance = np.absolute(real_transition_matrix.reshape(-1) -
                          perturbed_transition_matrix.reshape(-1))
print(f"Original distance is {np.sum(distance)}")

for i in range(20):
    real = np.dot(real, real_transition_matrix)
    perturbed = np.dot(perturbed, perturbed_transition_matrix)
    distance = np.absolute(real.reshape(-1) -
                              perturbed.reshape(-1))
    print(f"Distance vector is {np.sum(distance)}")

Original distance is 1.9881915103578964
Distance vector is 2.2084628286957586
Distance vector is 2.000540563312738
Distance vector is 1.7331799133806454
Distance vector is 1.546154574359751
Distance vector is 1.4615472078743055
Distance vector is 1.4324649367456694
Distance vector is 1.4441218373425508
Distance vector is 1.4631003663278965
Distance vector is 1.476927065942491
Distance vector is 1.4870632075173718
Distance vector is 1.4945247869754958
Distance vector is 1.5000323654212233
Distance vector is 1.5041045438423328
Distance vector is 1.5071184993776963
Distance vector is 1.509350530211577
Distance vector is 1.511003999725247
Distance vector is 1.5122290419926054
Distance vector is 1.5131366987081099
Distance vector is 1.5138091859015383
Distance vector is 1.5143074118460875
